paths:
  raw_dir:     "/data/home/quj_lab/zhangyuxin/01-project/001.meth/02.data/X101SC26072106-Z02-F006/01.RawData"
  trim_dir:    "/data/home/quj_lab/zhangyuxin/01-project/001.meth/04.results/01_DNAm_bismark/01_trim"
  map_dir:     "/data/home/quj_lab/zhangyuxin/01-project/001.meth/04.results/01_DNAm_bismark/02_map/"
  unique_dir:  "/data/home/quj_lab/zhangyuxin/01-project/001.meth/04.results/01_DNAm_bismark/03_unique"
  meth_dir:    "/data/home/quj_lab/zhangyuxin/01-project/001.meth/04.results/01_DNAm_bismark/04_meth"
  hmeth_dir:    "/data/home/quj_lab/zhangyuxin/01-project/001.meth/04.results/01_DNAm_bismark/04_meth"
  qc_dir:    "/data/home/quj_lab/zhangyuxin/01-project/001.meth/04.results/01_DNAm_bismark/05_qc"
  logs_dir:    "/data/home/quj_lab/zhangyuxin/01-project/001.meth/04.results/01_DNAm_bismark/logs"
  genome:      "/data/home/quj_lab/zhangyuxin/03-database/hg38_lambda/index/bismark_index"

trim:
  length: 50
  quality: 30

map:
  threads: 20

unique:
  threads: 24

meth:
  threads: 20
  buffer_size: "10G"